CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL UNIQUE,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories ON DELETE CASCADE,
    user_id bigint  NOT NULL REFERENCES users ON DELETE CASCADE,
    title varchar NOT NULL,
    annotation varchar NOT NULL,
    description varchar NOT NULL,
    event_date timestamp NOT NULL,
    location_lat float NOT NULL,
    location_lon float NOT NULL,
    paid boolean NOT NULL,
    participant_limit int NOT NULL,
    request_moderation boolean NOT NULL,
    state varchar NOT NULL,
    created_on timestamp NOT NULL,
    published_on timestamp
);