CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL UNIQUE,
    name varchar(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title varchar(120) NOT NULL,
    annotation varchar(2000) NOT NULL,
    description varchar(7000) NOT NULL,
    event_date timestamp NOT NULL,
    location_lat float NOT NULL,
    location_lon float NOT NULL,
    paid boolean NOT NULL DEFAULT FALSE,
    participant_limit int NOT NULL DEFAULT 0,
    request_moderation boolean NOT NULL DEFAULT TRUE,
    state varchar(20) NOT NULL DEFAULT 'PENDING',
    created_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_on timestamp
);

CREATE INDEX IF NOT EXISTS idx_events_state ON events(state);
CREATE INDEX IF NOT EXISTS idx_events_category ON events(category_id);
CREATE INDEX IF NOT EXISTS idx_events_user ON events(user_id);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date);