CREATE TABLE IF NOT EXISTS stat_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app varchar NOT NULL,
  uri varchar NOT NULL,
  ip varchar NOT NULL,
  event_date timestamp  NOT NULL
);